### PR TITLE
Move ConnectionSpec to be part of the generic Connection client pkg

### PR DESCRIPTION
**Pull request by zgalor**

### CODE REVIEW

**Comment by zgalor** [comment]
@jhernand @yaacov please review

**Comment by yaacov** [comment]
@jhernand @zgalor the hi, `ConnectionSpec` has STOMP specific args ( e.g. it has host, port, tls that other backends may not need or have and lack other ... ), I think it will nicer to have a generic `RequesterSpec`/`ResponderSpec` thay may include/implement/other a `ConnectionSpec`  , WDYT ?

**Comment by elad661** [comment]
I agree with @yaacov. While host, port and tls can be shared between backends, but other backends might have more/different parameters.

I think it's best if each backend will have its own spec with the arguments it needs and supports.

**Comment by jhernand** [comment]
I think that the connection spec should have fields for the parameters that we expect to be common, including all the ones that we currently have. If a particular implementation needs something else then they should be provided as name/value pairs:

```go
type ConnectionSpec {
  // Parameters common go all kinds of connections:
  Host string
  Port int
  ...

  // Room for parameters specific to certain connections:
  Properties map[string]interface{}
}
```

For example, if in the future we have an specific implementation that supports Kerberos authentication, it could create the connection like this:

```go
connection, err := client.NewConnection(&client.ConnectionSpec{
  Host: "myhost",
  Port: 123,
  Properties: map[string]interface{} {
    "kerberos": true,
  },
})
```

This allows for parameters specific to the particular implementation, and does not require the client application to import that specific implementation.

These `properties` could even be propagated from the command line of the client application, or from a configuration file:

```
$ messaging-client --host myhost --port 123 --property kerberos=true ...
```

Adding that new `Properties` field is something that we can do later, no need to do it as part of this pull request.

**Pull request merged**
